FROM ubuntu:14.10

RUN apt-get update && apt-get install -y less openjdk-7-jre-headless
RUN wget -q -0- http://d3kbcqa49mib13.cloudfront.net/spark-1.1.0-bin-hadoop2.4.tgz | tar xz && rm spark-1.1.0-bin-hadoop2.4.tgz 

